on:
  push:
    branches:
      - master
  pull_request:
    types:
      - "closed"
    branches:
      - master
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  release:
    uses: ./.github/workflows/release.yaml
    needs: [test]
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
